FAQ_SEMANTIC_PASSAGES: dict[str, str] = {
    "Де розташований The Meridian?": "The Meridian Casino and Resort is located on the Las Vegas Strip in Nevada.",
    "Коли працює казино?": "The casino is open twenty four hours a day, seven days a week.",
    "О котрій заселення та чи можливе раннє заселення?": "Hotel check-in and room access begin at 4 PM. Guests may get their room earlier when availability permits.",
    "О котрій виселення та чи можливе пізнє виселення?": "Hotel check-out is at 11 AM. Late departure is available for suite guests.",
    "Скільки коштує valet-паркування?": "Valet parking is free for hotel guests and costs 25 dollars for visitors.",
    "Чи є безкоштовне самостійне паркування?": "Self parking is free for every hotel guest and visitor.",
    "Який дрескод у The Meridian?": "The resort dress code is smart casual. Aurelia and Eclipse Lounge require formal attire.",
    "Які вікові обмеження діють у комплексі?": "Guests must be 21 or older for the casino and bars. The hotel and family restaurants welcome children, teenagers, and guests of every age.",
    "Чи є Wi-Fi?": "Complimentary Wi-Fi is available throughout the resort. Suites include premium high-speed internet.",
    "Які слот-машини є в казино?": "The casino has more than 2,000 slot machines, penny to 1,000 dollar bets, video slots, classic reels, and progressive jackpots up to 4.2 million dollars.",
    "Які столи для блекджеку доступні?": "There are 40 blackjack tables with 25 to 10,000 dollar minimums, single deck, six deck, and Spanish 21 games.",
    "Коли працює покерна кімната і які ігри доступні?": "The poker room is open 24/7 with Texas Hold'em, Omaha, Seven Card Stud, and daily 200 dollar tournaments at 11 AM and 7 PM.",
    "Яка рулетка доступна?": "Twelve roulette tables offer American, European, and French roulette with minimum bets from 15 dollars.",
    "Де можна грати в бакару?": "Baccarat is available at eight main casino tables and four private high-limit tables, with minimum bets from 50 dollars or 5,000 dollars in high limit.",
    "Чи є крепс і уроки гри?": "The casino has six craps tables with 15 dollar minimums and free daily craps lessons at 10 AM.",
    "Що пропонує Sports Book?": "The Sports Book is an 80-seat theater with a 40-foot screen and full bar. Mobile sports betting is available through the Meridian app.",
    "Як потрапити до High Limit Salon?": "The private High Limit Salon has personal hosts, a butler, dining, and private restrooms. Access requires an invitation or a 50,000 dollar credit line.",
    "Як працює Meridian Rewards?": "Meridian Rewards is the casino loyalty and players club. Guests earn points from gaming and progress through Gold, Platinum, Diamond, and invitation-only Black tiers.",
    "Що входить у Deluxe Room?": "A Deluxe Room is 450 square feet with one king or two queen beds, city or pool views, and rates from 299 dollars per night.",
    "Що входить у Premier Room?": "A Premier Room is 550 square feet with a king bed, sitting area, Strip view, and rates from 449 dollars per night.",
    "Що входить у Luxury Suite?": "A Luxury Suite is 900 square feet with a separate living room and marble bathroom with a deep soaking tub, from 799 dollars per night.",
    "Що входить у Penthouse Suite?": "The Penthouse Suite is an 1,800 square foot hotel room with two bedrooms, dining room, butler pantry, and a private outdoor terrace or balcony, from 2,500 dollars per night.",
    "Що входить у Chairman’s Villa?": "The Chairman's Villa is 4,500 square feet with three bedrooms, a private swimming pool, optional personal chef, and 24/7 butler. Price is available on request.",
    "Чи є доступні номери для гостей з інвалідністю?": "Accessible rooms exist in every category with roll-in showers, lowered fixtures, and visual alerts. Request accessibility when booking.",
    "Розкажіть про ресторан Aurelia.": "Aurelia is the signature two Michelin star fine-dining restaurant serving modern French cuisine by chef Marcus Webb. Dinner is 6 to 10 PM, reservations and formal attire required.",
    "Розкажіть про ресторан Silk Road.": "Silk Road is a pan-Asian restaurant where guests can eat sushi from a sushi bar, robata grill dishes, and dim sum. Open daily 11 AM to 11 PM.",
    "Розкажіть про The Steakhouse.": "The Steakhouse serves classic American dry-aged beef steaks and fresh seafood from 5 to 11 PM. Reservations are recommended.",
    "Коли працює Café Meridian?": "Cafe Meridian is a casual all-day restaurant with a breakfast buffet from 7 to 11 AM and lunch and dinner until midnight. No reservation required.",
    "Коли працює Pool Bar & Grill?": "Pool Bar and Grill serves burgers, salads, and cocktails from 10 AM to 6 PM seasonally and is only for hotel guests.",
    "Розкажіть про Eclipse Lounge.": "Eclipse Lounge is a rooftop bar with Las Vegas Strip views, cocktails, and champagne. Open 5 PM to 2 AM with formal attire after 8 PM.",
    "Розкажіть про The Vault.": "The Vault is a whiskey and cigar lounge with more than 400 whiskies and a premium cigar humidor. Open 4 PM to 2 AM for guests aged 21 and over.",
    "Чи є бари в казино та безкоштовні напої?": "The casino has six bars. Complimentary drinks are served to active gamblers and full bar service is available.",
    "Коли працює Meridian Spa?": "Meridian Spa and salon provides massages, facials, body treatments, and steam suites from 8 AM to 8 PM. Book 24 hours ahead.",
    "Коли працює фітнес-центр?": "The fitness center and gym are open 24 hours for hotel guests, including after midnight. Guests can work out with Peloton bikes, free weights, yoga, and personal trainers.",
    "Які басейни є в The Meridian?": "The resort has three swimming pools, including an adults-only infinity pool. Pools are open 8 AM to 8 PM and cabanas start at 300 dollars per day.",
    "Що проходить у Meridian Theater?": "Meridian Theater has 1,200 seats and residencies by internationally known artists. Tickets start at 95 dollars and VIP packages are available.",
    "Коли працює Nightclub NOVA?": "NOVA nightclub opens Friday and Saturday from 10:30 PM to 4 AM. Entry is 50 dollars and tables start at 2,000 dollars.",
    "Які весільні пакети пропонує The Meridian?": "Wedding venues range from an intimate chapel to a grand ballroom. Wedding packages cost 5,000 to 150,000 dollars and include a coordinator.",
    "Чи можна провести приватну або корпоративну подію?": "Private and corporate events can use meeting rooms and ballrooms from 500 to 15,000 square feet with catering, audiovisual services, and corporate rates.",
    "Які пакети є для дня народження, річниці або освідчення?": "Birthday, anniversary, romantic proposal, and engagement celebrations start at 500 dollars with a room upgrade, champagne, custom cake, and dining credit. Give 72 hours notice.",
    "Які пакети є для парубочого або дівич-вечора?": "Bachelor and bachelorette VIP packages include a suite, nightclub table, pool cabana, and spa credits from 3,000 dollars, booked one week ahead.",
    "Яка партнерська знижка в Carbone?": "Carbone is an Italian fine-dining restaurant five minutes away. Meridian room-key holders receive 15 percent off food and priority reservations.",
    "Яка партнерська знижка в Omega Mart?": "Meridian guests receive 10 dollars off admission to the Omega Mart interactive art experience.",
    "Яка партнерська знижка у Vegas Nights Aviation?": "Meridian guests receive 20 percent off Las Vegas Strip helicopter tours from Vegas Nights Aviation and complimentary champagne.",
    "Яка партнерська пропозиція в Top Golf Las Vegas?": "Top Golf Las Vegas gives Meridian guests one free hour when they book two hours.",
    "Яка партнерська знижка в Spa Aquae at JW Marriott?": "Spa Aquae at JW Marriott gives Meridian guests 10 percent off treatments when Meridian Spa is fully booked.",
    "Яка партнерська пропозиція у Fremont Street Experience?": "Meridian guests receive a VIP skip-the-line SlotZilla pass at Fremont Street Experience.",
}
